services:
  steam_data:
    build: .
    container_name: steam_data_analysis_spark_llm
    restart: "no"
    network_mode: "host"
    working_dir: /app
    volumes:
      - ./output:/output
      - ./data:/data
    environment:
      - LLM_API_URL=http://127.0.0.1:1234/v1/chat/completions